//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetHealthServicePrototype.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PetHealthServiceEntities : DbContext
    {
        public PetHealthServiceEntities()
            : base("name=PetHealthServiceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnimalType> AnimalType { get; set; }
        public virtual DbSet<Pet> Pet { get; set; }
        public virtual DbSet<Tip> Tip { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
